In [8]:
#wap to create an empty and a full NumPy array
import numpy as np
empty_arr=np.empty((1,1))
full_arr=np.full((3,3), 2)
print("empty array:",empty_arr)
print("full array:",full_arr)

empty array: [[1.]]
full array: [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [12]:
#wap to remove rows in numpy array that contains non numeric values
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[np.nan,np.nan,np.nan,np.nan,np.nan]])
print("Values:",arr)
print("Removing non numeric values:",arr[~np.isnan(arr).any(axis=1)])

Values: [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [nan nan nan nan nan]]
Removing non numeric values: [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [26]:
#wap to find the number of occurrences of sequence in a numpy array
arr=np.array([[1,2,3,4],[2,3,4,5],[4,2,3,4],[2,3,4,5]])
result=repr(arr).count("2, 3")
print(result)

4


In [27]:
#wap to find the most frequent value in a numpy array
arr=np.array([1,2,3,4,5,3,5,4,5,6,1,5,5,2,7,8,2])
print("Original data:",arr)
print("Most frequent(repeated) value in the array:",np.bincount(arr).argmax())

Original data: [1 2 3 4 5 3 5 4 5 6 1 5 5 2 7 8 2]
Most frequent(repeated) value in the array: 5


In [29]:
#wap to bulid an array of add of two numpy arrays
#concatenate
arr1=([1,2,3,4,5,])
arr2=([6,7,8,9,10])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
#adding
arr1=([1,2,3])
arr2=([4,5,6])
print("1st array:",arr1)
print("2nd array:",arr2)
out=np.add(arr1,arr2)
print("adding of two array:",out)

1st array: [1, 2, 3]
2nd array: [4, 5, 6]
adding of two array: [5 7 9]


In [32]:
#wap to return the indices of elements where the given condition is satisfied
arr=np.array([1,2,3,4,5,6,7,8,9])
condition=arr<5
indicies=np.where(condition)
print("original data:",arr)
print("indices of elements:",condition)

original data: [1 2 3 4 5 6 7 8 9]
indices of elements: [ True  True  True  True False False False False False]


In [1]:
import numpy as np
#wap to multiplying a matrix(numpy array) by a scalar
arr=np.array([[1,2,3],[4,5,6]])
scalar=3
matrix=arr*scalar
print("original data:",arr)
print("scalar:",scalar)
print("multiplying a matrix results:",matrix)

original data: [[1 2 3]
 [4 5 6]]
scalar: 3
multiplying a matrix results: [[ 3  6  9]
 [12 15 18]]


In [3]:
#wap to array redimensioning of giving data a=np.array([[2.5,3.8,1.5],[4.7,2.9,1.56]])
a=np.array([[2.5,3.8,1.5],[4.7,2.9,1.56]])
arr=a.reshape(3,2)
print("original data:",a)
print("reshaped data:",arr)

original data: [[2.5  3.8  1.5 ]
 [4.7  2.9  1.56]]
reshaped data: [[2.5  3.8 ]
 [1.5  4.7 ]
 [2.9  1.56]]


In [4]:
#wap to obtaining boolean array from binary array of given data a=np.array([[1,0,0],[1,1,1],[0,0,0]])
a=np.array([[1,0,0],[1,1,1],[0,0,0]])
boolean_array=a==1
print("binary array:",a)
print("boolean array:",boolean_array)

binary array: [[1 0 0]
 [1 1 1]
 [0 0 0]]
boolean array: [[ True False False]
 [ True  True  True]
 [False False False]]


In [5]:
#wap to horizontal stacking of numpy arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [7]:
#array generation of random integers within a special range
import random
print("random integers between 0 and 9:")
for i in range(1,10):
    y=random.randrange(10)
    print(y)

random integers between 0 and 9:
6
9
9
4
3
1
1
8
3


In [11]:
#matrix multiplication of given data a=np.array([[1,2,3],[4,5,6],[7,8,9]]) b=np.array([[2,3,4],[5,6,7],[8,9,10]])
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[2,3,4],[5,6,7],[8,9,10]])
result=np.multiply(a,b)
print("Matrix a:",a)
print("Matrix b:",b)
print("product:",result)

Matrix a: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix b: [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
product: [[ 2  6 12]
 [20 30 42]
 [56 72 90]]
